"""add summary fields to conversation

Revision ID: 619d48a9dd9c
Revises: 87cdcd5520f9
Create Date: 2025-10-30 23:38:42.876728+00:00

"""
import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from config import MEMORY_EMBED_DIM

# revision identifiers, used by Alembic.
revision = '619d48a9dd9c'
down_revision = '87cdcd5520f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # These objects existed in the development database that generated this
    # revision, but not in the canonical initial migration. Conditional DDL
    # keeps both upgrade paths valid, including a brand-new database.
    op.execute("DROP INDEX IF EXISTS llama_pg_vector_store_idx_1")
    op.execute("DROP TABLE IF EXISTS data_llama_pg_vector_store")
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('last_summarized_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['last_summarized_message_id'], ['id'], ondelete='SET NULL')
    op.execute("DROP INDEX IF EXISTS ix_messages_log_user_created")
    op.execute("DROP INDEX IF EXISTS ix_messages_user_user_created")
    op.execute(
        "ALTER TABLE IF EXISTS users "
        "DROP CONSTRAINT IF EXISTS users_active_persona_id_fkey"
    )
    op.execute("ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS active_persona_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_persona_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_active_persona_id_fkey'), 'users', 'personas', ['active_persona_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_messages_user_user_created'), 'messages_user', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_log_user_created'), 'messages_log', ['user_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'last_summarized_message_id')
    op.drop_column('conversations', 'summary')
    op.create_table('data_llama_pg_vector_store',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=MEMORY_EMBED_DIM), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_llama_pg_vector_store_pkey'))
    )
    op.create_index(op.f('llama_pg_vector_store_idx_1'), 'data_llama_pg_vector_store', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    # ### end Alembic commands ###